server:
      port: 8099  #配置端口
      address : localhost
      session-timeout: 30
      tomcat.max-threads: 0
      tomcat.uri-encoding: UTF-8

spring:
      data:  #数据库配置
            hbase:
                    zkQuorum: 172.16.2.134:2181
                    zkBasePath: /hbase
                    rootDir: file:///home/hbase-1.2.2

      devtools:
              restart:
                      enabled: true #热部署生效
                      additional-paths: spring-boot-jpa-page1/src/main/java  #设置重启的目录
#                      exclude: WEB-INF/**   #classpath目录下的WEB-INF文件夹内容修改不重启
# LOGGING
logging:
        level:
              root: INFO
              org:
                  springframework:
                                    web: DEBUG
                  hibernate: DEBUG
#        path: F:\\
#        file: log.log
              com:
                  ibatis: DEBUG
debug: true













